name: Run lint and static analyis checks
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: plus3it/actions-workflows/.github/workflows/lint.yml@0a03f75193a010b3532cc90e8ad0b15a09ed33c1

  golint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: 'go.mod'

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run go linter
        run: make golint
